/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const ExecutionLogEntry = IDL.Record({
  'status' : IDL.Text,
  'iconType' : IDL.Text,
  'stepName' : IDL.Text,
  'timestamp' : Time,
});
export const Settings = IDL.Record({
  'googleSheetsId' : IDL.Text,
  'slackWebhookUrl' : IDL.Text,
  'sheetTabName' : IDL.Text,
});
export const TaskHistoryEntry = IDL.Record({
  'taskId' : IDL.Nat,
  'timestamp' : Time,
  'success' : IDL.Bool,
  'commandText' : IDL.Text,
});

export const idlService = IDL.Service({
  'addExecutionLog' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTaskHistory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'clearExecutionLogs' : IDL.Func([], [], []),
  'clearTaskHistory' : IDL.Func([], [], []),
  'deleteTaskById' : IDL.Func([IDL.Nat], [], []),
  'getExecutionLogs' : IDL.Func([], [IDL.Vec(ExecutionLogEntry)], ['query']),
  'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
  'getTaskById' : IDL.Func([IDL.Nat], [TaskHistoryEntry], ['query']),
  'getTaskHistory' : IDL.Func([], [IDL.Vec(TaskHistoryEntry)], ['query']),
  'updateSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const ExecutionLogEntry = IDL.Record({
    'status' : IDL.Text,
    'iconType' : IDL.Text,
    'stepName' : IDL.Text,
    'timestamp' : Time,
  });
  const Settings = IDL.Record({
    'googleSheetsId' : IDL.Text,
    'slackWebhookUrl' : IDL.Text,
    'sheetTabName' : IDL.Text,
  });
  const TaskHistoryEntry = IDL.Record({
    'taskId' : IDL.Nat,
    'timestamp' : Time,
    'success' : IDL.Bool,
    'commandText' : IDL.Text,
  });
  
  return IDL.Service({
    'addExecutionLog' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTaskHistory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'clearExecutionLogs' : IDL.Func([], [], []),
    'clearTaskHistory' : IDL.Func([], [], []),
    'deleteTaskById' : IDL.Func([IDL.Nat], [], []),
    'getExecutionLogs' : IDL.Func([], [IDL.Vec(ExecutionLogEntry)], ['query']),
    'getSettings' : IDL.Func([], [IDL.Opt(Settings)], ['query']),
    'getTaskById' : IDL.Func([IDL.Nat], [TaskHistoryEntry], ['query']),
    'getTaskHistory' : IDL.Func([], [IDL.Vec(TaskHistoryEntry)], ['query']),
    'updateSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };