/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsSummary {
  'mostUsedCommands' : Array<string>,
  'totalTasks' : bigint,
  'successCount' : bigint,
  'failureCount' : bigint,
}
export interface Credential {
  'service' : string,
  'value' : string,
  'name' : string,
}
export interface ExecutionLogEntry {
  'status' : string,
  'iconType' : string,
  'stepName' : string,
  'timestamp' : Time,
}
export interface SavedAgent {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'command' : string,
  'triggerCount' : bigint,
}
export interface ScheduledTask {
  'id' : bigint,
  'name' : string,
  'enabled' : boolean,
  'command' : string,
  'nextRun' : Time,
  'frequency' : string,
}
export interface Settings {
  'googleSheetsId' : string,
  'slackWebhookUrl' : string,
  'sheetTabName' : string,
}
export interface TaskHistoryEntry {
  'taskName' : string,
  'taskId' : bigint,
  'timestamp' : Time,
  'success' : boolean,
  'commandText' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addCredential' : ActorMethod<[string, string, string], undefined>,
  'addExecutionLog' : ActorMethod<[string, string, string], undefined>,
  'addSavedAgent' : ActorMethod<[bigint, string, string], undefined>,
  'addScheduledTask' : ActorMethod<
    [bigint, string, string, string, Time],
    undefined
  >,
  'addTaskHistory' : ActorMethod<[bigint, string, string, boolean], undefined>,
  'clearExecutionLogs' : ActorMethod<[], undefined>,
  'clearTaskHistory' : ActorMethod<[], undefined>,
  'deleteCredential' : ActorMethod<[string], undefined>,
  'deleteSavedAgent' : ActorMethod<[bigint], undefined>,
  'deleteScheduledTask' : ActorMethod<[bigint], undefined>,
  'deleteTaskById' : ActorMethod<[bigint], undefined>,
  'getAnalyticsSummary' : ActorMethod<[], AnalyticsSummary>,
  'getCredentialByName' : ActorMethod<[string], [] | [Credential]>,
  'getCredentials' : ActorMethod<[], Array<Credential>>,
  'getExecutionLogs' : ActorMethod<[], Array<ExecutionLogEntry>>,
  'getSavedAgentById' : ActorMethod<[bigint], [] | [SavedAgent]>,
  'getSavedAgents' : ActorMethod<[], Array<SavedAgent>>,
  'getScheduledTaskById' : ActorMethod<[bigint], [] | [ScheduledTask]>,
  'getScheduledTasks' : ActorMethod<[], Array<ScheduledTask>>,
  'getSettings' : ActorMethod<[], [] | [Settings]>,
  'getTaskById' : ActorMethod<[bigint], TaskHistoryEntry>,
  'getTaskHistory' : ActorMethod<[], Array<TaskHistoryEntry>>,
  'updateCredential' : ActorMethod<[string, string], undefined>,
  'updateSavedAgent' : ActorMethod<[bigint, SavedAgent], undefined>,
  'updateScheduledTask' : ActorMethod<[bigint, ScheduledTask], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];